### ISSUE TITLE
Correction P4

### ISSUE THREAD

**Issue by lecascyril** [ncoquelet/RobinWood#54]
"Contrats : Super d'avoir été chercher la norme qui était dans ton cas d'usage, c'est important de savoir analyser et choisir. Il n'y a pas forcément un très grand nombre de fonctionnalités qui sortent de l'ordinaire, mais on est sur un travail tres maitrisé, où les nft se font bien, ou il y a beaucoup de logique de base de données, et donc c'est un travail très maitrisé
Tests : Les fichiers de tests dans le dossier contrat bon, pourquoi pas. Peu usuel mais pas dérangeant. Pour améliorer les tests, on peut utiliser les hooks before each pour lancer les fixtures dans les it d'un context et ainsi consacrer son test a la logique de test.
Front : Peut etre un point moins abouti : il est fonctionnel mais n'est pas forcément très travaillé d'un point de vue design. En revanche, avoir géré la gestion des metadata et des fichiers sur ipfs est très bien, cela donne d'autant plus de profondeur au projet.
Déploiement, video et GH dans les règles.
Super projet
9,5
"

**Comment by ncoquelet** [comment]
Merci merci beaucoup pour cette correction.
Comme je l'ai un peu fait comprendre, j'ai un peu galéré la dernière semaine avec de la fièvre et une impossibilité de me concentrer.
En gros à partir de mercredi, j'ai quasiment arrêté les devs, juste le fignolage pour livrer qqs choses de propre.
Il y avait tellement de chose que je voulais faire et que je n'ai pas eu le temps d'implémenter, j'était un peu deg sur le moment, je savais que je passais à coté du perfect :laughing: 

Pour répondre aux remarques:
Contrats:
- j'ai laissé le plus dur pour la fin et je n'ai pas pu le faire, mais bon je compte bien finir un jour au moins sur l'intégration des arbres de merkle et de la gestion des transports sur base d'erc20

Tests:
- la collocation des testU avec les contrats, c'est qqs chose que je vois de plus en plus sur des gros projets et ça ma séduit de gagner du temps pour passer du contrat au test et inversement. En java j'avais un plugin pour switcher avec un raccourci clavier, faudrait que je regarde si qqs chose existe pour solidity
- par contre le before each c'est définitivement non pour moi, les variables let au niveau du describe c'est clairement un error prone ! Pour initialiser un mock pourquoi pas. et encore ...

Front:
- globalement il y a 2/3 jours de dev max. la gestion des appels sur les rpc est catastrophique, mais ca reste un bon défis de remettre le nez dedans et d'optimiser tout ca !

En tout cas un grand merci a vous deux !
